# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FunToys.proto

require 'google/protobuf'


descriptor_data = "\n\rFunToys.proto\x12\x03rpc\"7\n\x06\x46unToy\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x1a\n\x0cGetFunToyReq\x12\n\n\x02id\x18\x01 \x01(\r\"-\n\rGetFunToyResp\x12\x1c\n\x07product\x18\x01 \x01(\x0b\x32\x0b.rpc.FunToy\".\n\rGetFunToysReq\x12\x0e\n\x06search\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r\"2\n\x11\x43reateFunToysResp\x12\x1d\n\x08products\x18\x01 \x03(\x0b\x32\x0b.rpc.FunToy2\xe5\x01\n\x07\x46unToys\x12\x34\n\tGetFunToy\x12\x11.rpc.GetFunToyReq\x1a\x12.rpc.GetFunToyResp\"\x00\x12\x31\n\nGetFunToys\x12\x12.rpc.GetFunToysReq\x1a\x0b.rpc.FunToy\"\x00\x30\x01\x12\x38\n\rCreateFunToys\x12\x0b.rpc.FunToy\x1a\x16.rpc.CreateFunToysResp\"\x00(\x01\x12\x37\n\x15\x43reateFunToysInStream\x12\x0b.rpc.FunToy\x1a\x0b.rpc.FunToy\"\x00(\x01\x30\x01\x42\x04Z\x02./b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Rpc
  FunToy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.FunToy").msgclass
  GetFunToyReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetFunToyReq").msgclass
  GetFunToyResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetFunToyResp").msgclass
  GetFunToysReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetFunToysReq").msgclass
  CreateFunToysResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.CreateFunToysResp").msgclass
end
