# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3
  cable:
    <<: *default
    database: db/development_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: db/development_cache.sqlite3
    migrations_paths: db/cache_migrate

test:
  primary:
    <<: *default
    database: db/test.sqlite3
  cable:
    <<: *default
    database: db/test_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: db/test_cache.sqlite3
    migrations_paths: db/cache_migrate

production:
  primary:
    <<: *default
    database: db/production.sqlite3
    # Uncomment and set these if needed
    # username: app
    # password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cable:
    <<: *default
    database: db/production_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: db/production_cache.sqlite3
    migrations_paths: db/cache_migrate
